services:
  sqlserver-training:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver-training
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Senha123"
      MSSQL_PID: "Developer"
    ports:
      - "1434:1433"
    volumes:
      - sqlserver_training_data:/var/opt/mssql
    restart: unless-stopped

volumes:
  sqlserver_training_data: